import requests
from bs4 import BeautifulSoup
import re
import argparse

BANNER = """
  ___      _           _      ______ _           _           
 / _ \    | |         (_)     |  ___(_)         | |          
/ /_\ \ __| |_ __ ___  _ _ __ | |_   _ _ __   __| | ___ _ __ 
|  _  |/ _` | '_ ` _ \| | '_ \|  _| | | '_ \ / _` |/ _ \ '__|
| | | | (_| | | | | | | | | | | |   | | | | | (_| |  __/ |   
\_| |_/\__,_|_| |_| |_|_|_| |_\_|   |_|_| |_|\__,_|\___|_|   
                                                             
Author: G4UR4V007
Version: 1.0
"""

# Common admin panel URLs
admin_panel_urls = [
    '/administrator/',
    '/admin1/',
    '/admin2/',
    '/admin3/',
    '/admin4/',
    '/admin5/',
    '/usuarios/',
    '/usuario/',
    '/moderator/',
    '/webadmin/',
    '/adminarea/',
    '/bb-admin/',
    '/adminLogin/',
    '/admin_area/',
    '/panel-administracion/',
    '/admin/',
    '/instadmin/',
    '/memberadmin/',
    '/administratorlogin/',
    '/adm/',
    '/admin/account.php',
    '/admin/index.php',
    '/admin/login.php',
    '/admin/admin.php',
    '/admin/account.php',
    '/admin_area/admin.php',
    '/admin_area/login.php',
    '/siteadmin/login.php',
    '/siteadmin/index.php',
    '/siteadmin/login.html',
    '/admin/account.html',
    '/admin/index.html',
    '/admin/login.html',
    '/admin/admin.html',
    '/admin_area/index.php',
    '/bb-admin/index.php',
    '/bb-admin/login.php',
    '/bb-admin/admin.php',
    '/admin/home.php',
    '/admin_area/login.html',
    '/admin_area/index.html',
    '/admin/controlpanel.php',
    '/admin.php',
    '/admincp/index.asp',
    '/admincp/login.asp',
    '/admincp/index.html',
    '/admin/account.html',
    '/adminpanel.html',
    '/webadmin.html',
    '/webadmin/index.html',
    '/webadmin/admin.html',
    '/webadmin/login.html',
    '/admin/admin_login.html',
    '/admin_login.html',
    '/panel-administracion/login.html',
    '/admin/cp.php',
    '/cp.php',
    '/administrator/index.php',
    '/administrator/login.php',
    '/nsw/admin/login.php',
    '/webadmin/login.php',
    '/admin/admin_login.php',
    '/admin_login.php',
    '/administrator/account.php',
    '/administrator.php',
    '/admin_area/admin.html',
    '/pages/admin/admin-login.php',
    '/admin/admin-login.php',
    '/admin-login.php',
    '/bb-admin/index.html',
    '/bb-admin/login.html',
    '/acceso.php',
    '/bb-admin/admin.html',
    '/admin/home.html',
    '/login.php',
    '/modelsearch/login.php',
    '/moderator.php',
    '/moderator/login.php',
    '/moderator/admin.php',
    '/account.php',
    '/pages/admin/admin-login.html',
    '/admin/admin-login.html',
    '/admin-login.html',
    '/controlpanel.php',
    '/admincontrol.php',
    '/admin/adminLogin.html',
    '/adminLogin.html',
    '/admin/adminLogin.html',
    '/home.html',
    '/rcjakar/admin/login.php',
    '/adminarea/index.html',
    '/adminarea/admin.html',
    '/webadmin.php',
    '/webadmin/index.php',
    '/webadmin/admin.php',
    '/admin/controlpanel.html',
    '/admin.html',
    '/admin/cp.html',
    '/cp.html',
    '/adminpanel.php',
    '/moderator.html',
    '/administrator/index.html',
    '/administrator/login.html',
    '/user.html',
    '/administrator/account.html',
    '/administrator.html',
    '/login.html',
    '/modelsearch/login.html',
    '/moderator/login.html',
    '/adminarea/login.html',
    '/panel-administracion/index.html',
    '/panel-administracion/admin.html',
    '/modelsearch/index.html',
    '/modelsearch/admin.html',
    '/admincontrol/login.html',
    '/adm/index.html',
    '/adm.html',
    '/moderator/admin.html',
    '/user.php',
    '/account.html',
    '/controlpanel.html',
    '/admincontrol.html',
    '/panel-administracion/login.php',
    '/wp-login.php',
    '/adminLogin.php',
    '/admin/adminLogin.php',
    '/home.php',
    '/admin.php',
    '/adminarea/index.php',
    '/adminarea/admin.php',
    '/adminarea/login.php',
    '/panel-administracion/index.php',
    '/panel-administracion/admin.php',
    '/modelsearch/index.php',
    '/modelsearch/admin.php',
    '/admincontrol/login.php',
    '/adm/admloginuser.php',
    '/admloginuser.php',
    '/admin2.php',
    '/admin2/login.php',
    '/admin2/index.php',
    '/usuarios/login.php',
    '/adm/index.php',
    '/adm.php',
    '/affiliate.php',
    '/adm_auth.php',
    '/memberadmin.php',
    '/administratorlogin.php',
    '/admin/account.cfm',
    '/admin/index.cfm',
    '/admin/login.cfm',
    '/admin/admin.cfm',
    '/admin/account.cfm',
    '/admin_area/admin.cfm',
    '/admin_area/login.cfm',
    '/siteadmin/login.cfm',
    '/siteadmin/index.cfm',
    '/siteadmin/login.html',
    '/admin/account.html',
    '/admin/index.html',
    '/admin/login.html',
    '/admin/admin.html',
    '/admin_area/index.cfm',
    '/bb-admin/index.cfm',
    '/bb-admin/login.cfm',
    '/bb-admin/admin.cfm',
    '/admin/home.cfm',
    '/admin_area/login.html',
    '/admin_area/index.html',
    '/admin/controlpanel.cfm',
    '/admin.cfm',
    '/admincp/index.asp',
    '/admincp/login.asp',
    '/admincp/index.html',
    '/admin/account.html',
    '/adminpanel.html',
    '/webadmin.html',
    '/webadmin/index.html',
    '/webadmin/admin.html',
    '/webadmin/login.html',
    '/admin/admin_login.html',
    '/admin_login.html',
    '/panel-administracion/login.html',
    '/admin/cp.cfm',
    '/cp.cfm',
    '/administrator/index.cfm',
    '/administrator/login.cfm',
    '/nsw/admin/login.cfm',
    '/webadmin/login.cfm',
    '/admin/admin_login.cfm',
    '/admin_login.cfm',
    '/administrator/account.cfm',
    '/administrator.cfm',
    '/admin_area/admin.html',
    '/pages/admin/admin-login.cfm',
    '/admin/admin-login.cfm',
    '/admin-login.cfm',
    '/bb-admin/index.html',
    '/bb-admin/login.html',
    '/bb-admin/admin.html',
    '/admin/home.html',
    '/login.cfm',
    '/modelsearch/login.cfm',
    '/moderator.cfm',
    '/moderator/login.cfm',
    '/moderator/admin.cfm',
    '/account.cfm',
    '/pages/admin/admin-login.html',
    '/admin/admin-login.html',
    '/admin-login.html',
    '/controlpanel.cfm',
    '/admincontrol.cfm',
    '/admin/adminLogin.html',
    '/acceso.cfm',
    '/adminLogin.html',
    '/admin/adminLogin.html',
    '/home.html',
    '/rcjakar/admin/login.cfm',
    '/adminarea/index.html',
    '/adminarea/admin.html',
    '/webadmin.cfm',
    '/webadmin/index.cfm',
    '/acceso.cgi',
    '/webadmin/admin.cgi',
    '/admin/controlpanel.html',
    '/admin.html',
    '/admin/cp.html',
    '/cp.html',
    '/adminpanel.cgi',
    '/moderator.html',
    '/administrator/index.html',
    '/administrator/login.html',
    '/user.html',
    '/administrator/account.html',
    '/administrator.html',
    '/login.html',
    '/modelsearch/login.html',
    '/moderator/login.html',
    '/adminarea/login.html',
    '/panel-administracion/index.html',
    '/panel-administracion/admin.html',
    '/modelsearch/index.html',
    '/modelsearch/admin.html',
    '/admincontrol/login.html',
    '/adm/index.html',
    '/adm.html',
    '/moderator/admin.html',
    '/user.cgi',
    '/account.html',
    '/controlpanel.html',
    '/admincontrol.html',
    '/panel-administracion/login.cgi',
    '/wp-login.cgi',
    '/adminLogin.cgi',
    '/admin/adminLogin.cgi',
    '/home.cgi',
    '/admin.cgi',
    '/adminarea/index.cgi',
    '/adminarea/admin.cgi',
    '/adminarea/login.cgi',
    '/panel-administracion/index.cgi',
    '/panel-administracion/admin.cgi',
    '/modelsearch/index.cgi',
    '/modelsearch/admin.cgi',
    '/admincontrol/login.cgi',
    '/adm/admloginuser.cgi',
    '/admloginuser.cgi',
    '/admin2.cgi',
    '/admin2/login.cgi',
    '/admin2/index.cgi',
    '/usuarios/login.cgi',
    '/adm/index.cgi',
    '/adm.cgi',
    '/affiliate.cgi',
    '/adm_auth.cgi',
    '/memberadmin.cgi',
    '/administratorlogin.cgi',
    '/admin/account.brf',
    '/admin/index.brf',
    '/admin/login.brf',
    '/admin/admin.brf',
    '/admin/account.brf',
    '/admin_area/admin.brf',
    '/admin_area/login.brf',
    '/siteadmin/login.brf',
    '/siteadmin/index.brf',
    '/siteadmin/index.brf',
    '/siteadmin/login.html',
    '/admin/account.html',
    '/admin/index.html',
    '/admin/login.html',
    '/admin/admin.html',
    '/admin_area/index.brf',
    '/bb-admin/index.brf',
    '/bb-admin/login.brf',
    '/bb-admin/admin.brf',
    '/admin/home.brf',
    '/admin_area/login.html',
    '/admin_area/index.html',
    '/admin/controlpanel.brf',
    '/admin.brf',
    '/admincp/index.asp',
    '/admincp/login.asp',
    '/admincp/index.html',
    '/admin/account.html',
    '/adminpanel.html',
    '/webadmin.html',
    '/webadmin/index.html',
    '/webadmin/admin.html',
    '/webadmin/login.html',
    '/admin/admin_login.html',
    '/admin_login.html',
    '/panel-administracion/login.html',
    '/admin/cp.brf',
    '/cp.brf',
    '/administrator/index.brf',
    '/administrator/login.brf',
    '/nsw/admin/login.brf',
    '/webadmin/login.brf',
    '/admin/admin_login.brf',
    '/admin_login.brf',
    '/administrator/account.brf',
    '/administrator.brf',
    '/acceso.brf',
    '/admin_area/admin.html',
    '/pages/admin/admin-login.brf',
    '/admin/admin-login.brf',
    '/admin-login.brf',
    '/bb-admin/index.html',
    '/bb-admin/login.html',
    '/bb-admin/admin.html',
    '/admin/home.html',
    '/login.brf',
    '/modelsearch/login.brf',
    '/moderator.brf',
    '/moderator/login.brf',
    '/moderator/admin.brf',
    '/account.brf',
    '/pages/admin/admin-login.html',
    '/admin/admin-login.html',
    '/admin-login.html',
    '/controlpanel.brf',
    '/admincontrol.brf',
    '/admin/adminLogin.html',
    '/adminLogin.html',
    '/admin/adminLogin.html',
    '/home.html',
    '/rcjakar/admin/login.brf',
    '/adminarea/index.html',
    '/adminarea/admin.html',
    '/webadmin.brf',
    '/webadmin/index.brf',
    '/acceso.cgi',
    '/webadmin/admin.cgi',
    '/admin/controlpanel.html',
    '/admin.html',
    '/admin/cp.html',
    '/cp.html',
    '/adminpanel.cgi',
    '/moderator.html',
    '/administrator/index.html',
    '/administrator/login.html',
    '/user.html',
    '/administrator/account.html',
    '/administrator.html',
    '/login.html',
    '/modelsearch/login.html',
    '/moderator/login.html',
    '/adminarea/login.html',
    '/panel-administracion/index.html',
    '/panel-administracion/admin.html',
    '/modelsearch/index.html',
    '/modelsearch/admin.html',
    '/admincontrol/login.html',
    '/adm/index.html',
    '/adm.html',
    '/moderator/admin.html',
    '/user.cgi',
    '/account.html',
    '/controlpanel.html',
    '/admincontrol.html',
    '/panel-administracion/login.cgi',
    '/wp-login.cgi',
    '/adminLogin.cgi',
    '/admin/adminLogin.cgi',
    '/home.cgi',
    '/admin.cgi',
    '/adminarea/index.cgi',
    '/adminarea/admin.cgi',
    '/adminarea/login.cgi',
    '/panel-administracion/index.cgi',
    '/panel-administracion/admin.cgi',
    '/modelsearch/index.cgi',
    '/modelsearch/admin.cgi',
    '/admincontrol/login.cgi',
    '/adm/admloginuser.cgi',
    '/admloginuser.cgi',
    '/admin2.cgi',
    '/admin2/login.cgi',
    '/admin2/index.cgi',
    '/usuarios/login.cgi',
    '/adm/index.cgi',
    '/adm.cgi',
    '/affiliate.cgi',
    '/adm_auth.cgi',
    '/memberadmin.cgi',
    '/administratorlogin.cgi',
]

def get_wordlist(url):
    """
    Generate a wordlist based on the website's content
    """
    try:
        response = requests.get(url)
        response.raise_for_status()
    except requests.RequestException as e:
        print(f"Error fetching the URL: {e}")
        return []

    soup = BeautifulSoup(response.content, 'html.parser')
    words = re.findall(r'\b\w+\b', soup.get_text())
    return list(set(words))

def find_admin_panel(url):
    """
    Try common admin panel URLs and generate a wordlist
    """
    print(BANNER)
    wordlist = get_wordlist(url)
    
    for admin_url in admin_panel_urls:
        full_url = url + admin_url
        try:
            response = requests.get(full_url)
            if response.status_code == 200:
                print(f"Found admin panel: {full_url}")
                return
        except requests.RequestException as e:
            print(f"Error checking {full_url}: {e}")

    print("No admin panel found. Generating wordlist...")
    with open('wordlist.txt', 'w') as f:
        for word in wordlist:
            f.write(word + '\n')
    print("Wordlist generated as 'wordlist.txt'.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Admin Panel Finder Tool')
    parser.add_argument('-u', '--url', help='Website URL (include http:// or https://)', required=True)
    args = parser.parse_args()
    find_admin_panel(args.url)